default_stages: [commit]

repos:
  - repo: https://github.com/psf/black
    rev: 23.12.1
    hooks:
      - id: black
        args: [--line-length=88]
        files: ['\.py$', '\.pyx$']
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.6.8
    hooks:
      - id: ruff
        args: [--fix]
        files: ['\.py$', '\.pyx$']
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v1.11.1
    hooks:
      - id: mypy
        args: [--strict, --install-types, --non-interactive]
        files: ['\.py$', '\.pyx$']
  - repo: https://github.com/astral-sh/trailing-whitespace
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
        files: ['\.py$', '\.pyx$']