# PlexiChat Client Configuration Example
# Copy this file to ~/.plexichat-client.yaml and customize as needed

# Server connection settings
server:
  url: "http://localhost:8000"
  timeout: "30s"
  retries: 3
  
# Authentication settings
auth:
  # API key for authentication (optional)
  api_key: ""
  
  # Default username (optional)
  username: ""
  
  # Auto-login on startup (requires stored credentials)
  auto_login: false
  
  # Session timeout
  session_timeout: "24h"

# Client behavior settings
client:
  # Verbose output by default
  verbose: false
  
  # Default output format (json, yaml, table, csv)
  output_format: "table"
  
  # Color output
  color: true
  
  # Concurrent requests limit
  concurrent_requests: 10
  
  # Default pagination size
  page_size: 20

# Chat settings
chat:
  # Default room to join
  default_room: "general"
  
  # Auto-join rooms on login
  auto_join_rooms: []
  
  # Message history limit
  history_limit: 100
  
  # Enable notifications
  notifications: true

# File upload settings
files:
  # Default upload directory
  upload_dir: "./uploads"
  
  # Default download directory
  download_dir: "./downloads"
  
  # Maximum file size (in MB)
  max_file_size: 100
  
  # Allowed file extensions
  allowed_extensions: [".txt", ".pdf", ".doc", ".docx", ".jpg", ".png", ".gif"]

# Security settings
security:
  # Verify SSL certificates
  verify_ssl: true
  
  # Enable request signing
  sign_requests: false
  
  # Rate limiting
  rate_limit:
    requests_per_minute: 60
    burst_limit: 10

# Monitoring and analytics
monitoring:
  # Enable performance metrics
  enable_metrics: false
  
  # Metrics collection interval
  metrics_interval: "30s"
  
  # Log level (debug, info, warn, error)
  log_level: "info"

# Advanced settings
advanced:
  # Custom headers to include in requests
  custom_headers: {}
  
  # Proxy settings
  proxy:
    enabled: false
    url: ""
    username: ""
    password: ""
  
  # TLS settings
  tls:
    insecure_skip_verify: false
    cert_file: ""
    key_file: ""
    ca_file: ""

# Plugin settings
plugins:
  # Enable plugin system
  enabled: true
  
  # Plugin directory
  plugin_dir: "./plugins"
  
  # Auto-load plugins
  auto_load: true
  
  # Enabled plugins
  enabled_plugins: []

# Scripting and automation
automation:
  # Script directory
  script_dir: "./scripts"
  
  # Enable scheduled tasks
  enable_scheduler: false
  
  # Default script timeout
  script_timeout: "5m"

# Development settings
development:
  # Enable debug mode
  debug: false
  
  # Mock server mode
  mock_mode: false
  
  # Test data directory
  test_data_dir: "./test-data"
