from .edge_computing_manager import (
from typing import Optional


    API,
    Auto-scaling,
    Automatic,
    Components:,
    Computing,
    Core,
    Distributed,
    Edge,
    EdgeComputingManager,
    EdgeComputingManager:,
    EdgeNode,
    Features:,
    Health,
    Intelligent,
    LoadLevel,
    LoadMetrics,
    Manager,
    Module,
    Multi-tier,
    Node,
    NodeType,
    Performance,
    PlexiChat,
    Predictive,
    Real-time,
    ScalingAction,
    ScalingDecision,
    This,
    Traffic,
    """,
    &,
    -,
    analytics,
    and,
    auto-scaling,
    automatic,
    balancing,
    based,
    caching,
    capabilities,
    collection,
    comprehensive,
    computing,
    demand,
    distribution,
    edge,
    endpoints,
    failover,
    for,
    functionality,
    geographic,
    get_edge_computing_manager,
    health,
    historical,
    integration,
    load,
    management,
    metrics,
    module,
    monitoring,
    node,
    on,
    optimization,
    patterns,
    performance,
    platform.,
    provides,
    resource,
    routing,
    scaling,
    system,
    the,
    traffic,
    with,
)

__all__ = [
    "EdgeComputingManager",
    "EdgeNode",
    "NodeType",
    "LoadLevel",
    "ScalingAction",
    "LoadMetrics",
    "ScalingDecision",
    "get_edge_computing_manager"
]

# Version information
__version__ = "1.0.0"
__author__ = "PlexiChat Development Team"
__description__ = "PlexiChat Performance & Edge Computing Module"
