"""
Type stubs for plugins_internal.py - Auto-Generated
==================================================

This file provides type hints for better IDE support when developing plugins.
Generated on: 2025-09-10T19:42:50.376697
"""

from typing import Any, Dict, List, Optional, Union, Callable, AsyncContextManager
from pathlib import Path

class PluginLogger:
    def __init__(self, plugin_name: str) -> None: ...
    def debug(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def info(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def warning(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def error(self, message: str, *args: Any, **kwargs: Any) -> None: ...
    def critical(self, message: str, *args: Any, **kwargs: Any) -> None: ...

class EventManager:
    def __init__(self, plugin_name: str) -> None: ...
    def emit(self, event_name: str, data: Any = None) -> None: ...
    def listen(self, event_name: str, handler: Callable) -> None: ...
    def unlisten(self, event_name: str, handler: Callable) -> None: ...

class ConfigManager:
    def __init__(self, plugin_name: str) -> None: ...
    def get_plugin_config(self, key: str, default: Any = None) -> Any: ...
    def set_plugin_config(self, key: str, value: Any) -> None: ...

class PermissionChecker:
    def __init__(self, plugin_name: str) -> None: ...
    def has_permission(self, permission_type: str) -> bool: ...
    def request_permission(self, permission_type: str, justification: str) -> str: ...

class SafeFileManager:
    def __init__(self, plugin_name: str, security_manager: Any) -> None: ...
    def open(self, filename: str, mode: str = 'r', **kwargs: Any) -> Any: ...
    async def upload_file(self, file_data: bytes, filename: str, **kwargs: Any) -> Any: ...
    async def get_file_data(self, file_id: str) -> Any: ...

class NetworkBroker:
    def __init__(self, plugin_name: str, security_manager: Any) -> None: ...
    async def get(self, url: str, **kwargs: Any) -> str: ...
    async def post(self, url: str, **kwargs: Any) -> str: ...
    async def close(self) -> None: ...

class PluginAPI:
    plugin_name: str
    logger: PluginLogger
    events: EventManager
    config: ConfigManager
    permissions: PermissionChecker
    files: SafeFileManager
    network: NetworkBroker
    
    def __init__(self, plugin_name: str) -> None: ...
    def secure_context(self) -> AsyncContextManager['PluginAPI']: ...
    def get_plugin_info(self) -> Dict[str, Any]: ...

# Exceptions
class PluginSecurityError(Exception): ...
class PluginPermissionError(PluginSecurityError): ...
class PluginAPIError(Exception): ...

# Functions
def create_plugin_api(plugin_name: str) -> PluginAPI: ...
def check_compatibility(required_version: Optional[str] = None) -> bool: ...
def get_sdk_info() -> Dict[str, str]: ...

# Constants
SDK_VERSION: str
PLEXICHAT_VERSION: str